// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3jtAPeQIKlR5F4Rxp8R0PzdXA6Je-e2E',
    appId: '1:148240534200:web:541b4097f478eff283824d',
    messagingSenderId: '148240534200',
    projectId: 'nice-village',
    authDomain: 'nice-village.firebaseapp.com',
    storageBucket: 'nice-village.firebasestorage.app',
    measurementId: 'G-GW0QVLRLCE',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRjnDDRA5xWBvPM9I7DfD4FKWELC21Mzc',
    appId: '1:148240534200:ios:6c4303b6b79a60a483824d',
    messagingSenderId: '148240534200',
    projectId: 'nice-village',
    storageBucket: 'nice-village.firebasestorage.app',
    iosBundleId: 'com.example.niceVillage',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3jtAPeQIKlR5F4Rxp8R0PzdXA6Je-e2E',
    appId: '1:148240534200:web:6e5aa0884998f7d583824d',
    messagingSenderId: '148240534200',
    projectId: 'nice-village',
    authDomain: 'nice-village.firebaseapp.com',
    storageBucket: 'nice-village.firebasestorage.app',
    measurementId: 'G-5FNP3J954Z',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRjnDDRA5xWBvPM9I7DfD4FKWELC21Mzc',
    appId: '1:148240534200:ios:6c4303b6b79a60a483824d',
    messagingSenderId: '148240534200',
    projectId: 'nice-village',
    storageBucket: 'nice-village.firebasestorage.app',
    iosBundleId: 'com.example.niceVillage',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBddtPgbtUKk8_gABqRwVaNsW9OXZ9aMC8',
    appId: '1:148240534200:android:1af396306b39174b83824d',
    messagingSenderId: '148240534200',
    projectId: 'nice-village',
    storageBucket: 'nice-village.firebasestorage.app',
  );

}